data_ingestion:
  root_dir: data/data_ingestion
  source_url: https://github.com/KimaniKibuthu/text-summarizer/raw/main/data/corpus.7z
  local_data_dir: data/data_ingestion/data.7z
  unzip_dir: data/data_ingestion/raw_data

data_validation:
  root_dir: data/data_validation
  STATUS_FILE: data/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train.json", "test.json", "val.json"]

data_transformation:
  root_dir: data/data_transformation
  data_path: data/data_ingestion/raw_data
  tokenizer_name: google/pegasus-cnn_dailymail

model_training:
  root_dir: models/model_training
  data_dir: data/data_ingestion/raw_data/transformers_format_data
  model_ckpt: google/pegasus-cnn_dailymail

model_evaluation:
  root_dir: models/model_evaluation
  data_dir: data/data_ingestion/raw_data/transformers_format_data
  model_path: models/model_training/model/pegasus-summarization-model
  tokenizer_path: models/model_training/tokenizer/tokenizer