data_ingestion:
  root_dir: data/data_ingestion
  source_url: https://github.com/KimaniKibuthu/text-summarizer/raw/main/TextSummarizer/data/corpus.7z
  local_data_dir: data/data_ingestion/data.7z
  unzip_dir: data/data_ingestion/raw_data
